{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggragged
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggragged_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggragged/ggragged_{{ version }}.tar.gz
  sha256: 35d9aebed0dd4c443198c978b82685fad3f8b9a5895fe9ee3c5e684b35fe179e

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-gtable
    - r-rlang
    - r-vctrs
  run:
    - r-base
    - r-ggplot2
    - r-gtable
    - r-rlang
    - r-vctrs

test:
  commands:
    - $R -e "library('ggragged')"           # [not win]
    - "\"%R%\" -e \"library('ggragged')\""  # [win]

about:
  home: https://github.com/mikmart/ggragged, https://mikmart.github.io/ggragged/
  license: MIT
  summary: Extend 'ggplot2' facets to panel layouts arranged in a grid with ragged edges. facet_ragged_rows()
    groups panels in rows of (potentially) varying lengths, facet_ragged_cols() does
    the same for columns. These can be useful, for example, to represent nested or partially
    crossed relationships between faceting variables.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
